<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="6" name="Default test" time="51.305" errors="0" timestamp="2025-03-12T18:09:08 IST">
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC001_LoginWithValidCredentials" time="4.425"/>
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC002_LoginWithInValidCredentials" time="4.619"/>
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC002_LoginWithInValidCredentials" time="4.623"/>
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC002_LoginWithInValidCredentials" time="4.841"/>
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC005_LoginWithoutCredentials" time="4.446"/>
  <testcase classname="com.qaautomation.functionaltests.LoginTests" name="TC006_LoginWithEnter" time="5.187">
    <failure type="java.lang.AssertionError" message="expected [User or Password is valid] but found [Guru99 Bank Manager HomePage]">
      <![CDATA[java.lang.AssertionError: expected [User or Password is valid] but found [Guru99 Bank Manager HomePage]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qaautomation.commonactions.Commands.CompareStringAssertions(Commands.java:15)
at com.qaautomation.pages.LoginPageObjects.LoginWithEnterButton(LoginPageObjects.java:90)
at com.qaautomation.functionaltests.LoginTests.TC006_LoginWithEnter(LoginTests.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC006_LoginWithEnter -->
</testsuite> <!-- Default test -->
